name: Ruby Gem

on:
  push:
    branches: [ main ]

jobs:
  build_and_test:
    name: Build + test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

# Java 17 を使えるようにする
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: microsoft
    - name: Set up JRuby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: jruby
    - run: bundle install
    - run: gem install rspec
    - name: test
      run: |
        gem build *.gemspec
        gem install *.gem
        rspec sample/samplez.rb
  deploy:
    name: Publish
    runs-on: ubuntu-latest
    needs: build_and_test
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby 3.1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.1

    - name: Publish to GPR
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        gem build *.gemspec
        gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
      env:
        GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
        OWNER: ${{ github.repository_owner }}

#    - name: Publish to RubyGems
#      run: |
#        mkdir -p $HOME/.gem
#        touch $HOME/.gem/credentials
#        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
#        chmod 0600 $HOME/.gem/credentials
#        gem build *.gemspec
#        gem push --otp github *.gem
#      env:
#        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"

